# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clip.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nclip.proto\x12\x0b\x43LIPService\"7\n\x15ImageEmbeddingRequest\x12\x0e\n\x06imdata\x18\x01 \x01(\x0c\x12\x0e\n\x06imsize\x18\x02 \x03(\x05\"(\n\x14TextEmbeddingRequest\x12\x10\n\x08textdata\x18\x01 \x03(\t\"x\n\rImageTextData\x12\x32\n\x06imdata\x18\x01 \x01(\x0b\x32\".CLIPService.ImageEmbeddingRequest\x12\x33\n\x08textdata\x18\x02 \x01(\x0b\x32!.CLIPService.TextEmbeddingRequest\"%\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\x32\xed\x01\n\x0b\x43LIPService\x12N\n\x11ImageEmbeddingGet\x12\".CLIPService.ImageEmbeddingRequest\x1a\x13.CLIPService.Tensor\"\x00\x12L\n\x10TextEmbeddingGet\x12!.CLIPService.TextEmbeddingRequest\x1a\x13.CLIPService.Tensor\"\x00\x12@\n\x0bZeroShotCls\x12\x1a.CLIPService.ImageTextData\x1a\x13.CLIPService.Tensor\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_start=27
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_end=82
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_start=84
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_end=124
  _globals['_IMAGETEXTDATA']._serialized_start=126
  _globals['_IMAGETEXTDATA']._serialized_end=246
  _globals['_TENSOR']._serialized_start=248
  _globals['_TENSOR']._serialized_end=285
  _globals['_CLIPSERVICE']._serialized_start=288
  _globals['_CLIPSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
