# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import clip_pb2 as clip__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CLIPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageEmbeddingGet = channel.unary_unary(
                '/CLIPService.CLIPService/ImageEmbeddingGet',
                request_serializer=clip__pb2.ImageEmbeddingRequest.SerializeToString,
                response_deserializer=clip__pb2.Tensor.FromString,
                _registered_method=True)
        self.TextEmbeddingGet = channel.unary_unary(
                '/CLIPService.CLIPService/TextEmbeddingGet',
                request_serializer=clip__pb2.TextEmbeddingRequest.SerializeToString,
                response_deserializer=clip__pb2.Tensor.FromString,
                _registered_method=True)
        self.ZeroShotCls = channel.unary_unary(
                '/CLIPService.CLIPService/ZeroShotCls',
                request_serializer=clip__pb2.ImageTextData.SerializeToString,
                response_deserializer=clip__pb2.Tensor.FromString,
                _registered_method=True)


class CLIPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageEmbeddingGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextEmbeddingGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZeroShotCls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CLIPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageEmbeddingGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageEmbeddingGet,
                    request_deserializer=clip__pb2.ImageEmbeddingRequest.FromString,
                    response_serializer=clip__pb2.Tensor.SerializeToString,
            ),
            'TextEmbeddingGet': grpc.unary_unary_rpc_method_handler(
                    servicer.TextEmbeddingGet,
                    request_deserializer=clip__pb2.TextEmbeddingRequest.FromString,
                    response_serializer=clip__pb2.Tensor.SerializeToString,
            ),
            'ZeroShotCls': grpc.unary_unary_rpc_method_handler(
                    servicer.ZeroShotCls,
                    request_deserializer=clip__pb2.ImageTextData.FromString,
                    response_serializer=clip__pb2.Tensor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CLIPService.CLIPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CLIPService.CLIPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CLIPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageEmbeddingGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CLIPService.CLIPService/ImageEmbeddingGet',
            clip__pb2.ImageEmbeddingRequest.SerializeToString,
            clip__pb2.Tensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextEmbeddingGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CLIPService.CLIPService/TextEmbeddingGet',
            clip__pb2.TextEmbeddingRequest.SerializeToString,
            clip__pb2.Tensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZeroShotCls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CLIPService.CLIPService/ZeroShotCls',
            clip__pb2.ImageTextData.SerializeToString,
            clip__pb2.Tensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
